# Generated by Django 4.1.2 on 2022-10-20 20:47

from django.db import migrations
import useraccount.models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='favourite_color',
            field=useraccount.models.RGBcolorField(max_length=6, null=True),
        ),
    ]
