# Generated by Django 4.1.2 on 2022-10-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_useraccount_favourite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='profiles_photos'),
        ),
    ]
